title: Christopher
#logo: https://avatars.githubusercontent.com/u/130267192?s=400&u=980eb3386dc5c082e0b1619d8b38a707b66d6e8a&v=4
logo: https://pfp.nostr.build/16c06900f2d6aba8d0374247a2f47304421aedd9a1cb0e3ad3c855b8025bd394.png
#description: text below image
show_download: true
theme: jekyll-theme-minimal-mistakes
theme-color: dark 
name: Christopher
